# GitHub Sponsors & Funding Configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (up to 4 usernames)
github: [craftzcatdev]

# Patreon username
patreon: # craftzcatdev

# Ko-fi username
ko_fi: # craftzcatdev

# Open Collective username
open_collective: # craftzcatdev

# Tidelift package name (format: platform/package-name)
tidelift: # npm/astro-react-hybrid-template

# Community Bridge project name
community_bridge: # project-name

# Liberapay username
liberapay: # craftzcatdev

# IssueHunt username
issuehunt: # craftzcatdev

# Otechie username
otechie: # craftzcatdev

# LFX Crowdfunding project name
lfx_crowdfunding: # project-name

# Buy Me a Coffee username
custom: # ['https://www.buymeacoffee.com/craftzcatdev']

